### ISSUE TITLE
Create an object of Cookie class and pass a name and its value Using Servlet

### ISSUE THREAD

**Issue by Pankaj-Str** [Pankaj-Str/Servlet-Tutorial#1]

**Comment by OmkarVanjare** [comment]
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.Cookie;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import java.io.IOException;


public class CookieServlet extends HttpServlet {
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {


		Cookie usernameCookie = new Cookie("username","jhon_doe");
		
		usernameCookie.setMaxAge(3600);
		usernameCookie.setPath("/");
		
		response.addCookie(usernameCookie);
		
		response.setContentType("text/html");
		response.getWriter().println("Cookies Created and sent...."	);
	}

}

**Comment by SanjanaMore7** [comment]
package cookies;

import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.Cookie;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import java.io.IOException;

import java.io.IOException;

public class CookieServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
   
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// Create a cookie
        Cookie usernameCookie = new Cookie("username", "john_doe");
     // Set cookie properties
        usernameCookie.setMaxAge(3600); // Cookie lasts for 1 hour
        usernameCookie.setPath("/"); // Cookie is accessible from the entire context path
        response.addCookie(usernameCookie);
        response.setContentType("text/html");
        response.getWriter().println("Cookie created and sent.");
	}

}
